on: push
name: Test and deploy Golang
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Use Go 1.15.6
        uses: actions/checkout@master

      - name: test files
        uses: cedrickring/golang-action@1.6.0
        env:
          GO111MODULE: 'on'
        with:
          args: make test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ferpart/pokemon-rest-go:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: deploy to ClusterConfig
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: set image --record deployments/pokemonrest-deployment pokemonrest=docker.io/ferpart/pokemon-rest-go:latest
      - name: verify deployment
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          KUBECTL_VERSION: '1.15'
        with:
          args: '"rollout status deployments/pokemonrest-deployment"'
