on: push
name: Test Golang
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Use Go 1.15.6
        uses: actions/checkout@master

      - name: test files
        uses: cedrickring/golang-action@1.6.0
        env:
          GO111MODULE: 'on'
        with:
          args: make test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Go 1.15.6
        uses: actions/checkout@master

      - name: build files
        uses: cedrickring/golang-action@1.6.0
        env:
          GO111MODULE: 'on'
        with:
          args: make build
